export enum VALID_ENV_KEYS {
  OPENAI_API_KEY = "OPENAI_API_KEY",
  ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY",
  GOOGLE_GEMINI_API_KEY = "GOOGLE_GEMINI_API_KEY",
  MISTRAL_API_KEY = "MISTRAL_API_KEY",
  GROQ_API_KEY = "GROQ_API_KEY",
  PERPLEXITY_API_KEY = "PERPLEXITY_API_KEY",
  OPENROUTER_API_KEY = "OPENROUTER_API_KEY",
  OPENAI_ORGANIZATION_ID = "OPENAI_ORGANIZATION_ID"
}
